#This uses the dataset sent by Sylvie on September 9 2016 

#Strata_Q_sylvie <- read.csv("file:///D:/RProjects/UseIndi/data/strata_sylvie/stratsetq2_NA_0fill.csv", header=TRUE, na.strings = "NA", sep=",", as.is=T, strip.white=T)
#Strata_Q_sylvie <- read.csv("file:///D:/RProjects/UseIndi/data/strata_sylvie/Indi_C_s.csv", header=TRUE, na.strings = "NA", sep=",", as.is=T, strip.white=T)
IndiStrata_fillNA <- read.csv("file:///D:/RProjects/UseIndi/data/strata_sylvie//IndiStrata_fillNA.csv", header=TRUE, na.strings = "NA", sep=",", as.is=T, strip.white=T)
stratsetq2 <- read.csv("file:///D:/RProjects/UseIndi/data/strata_sylvie/stratsetq2.csv", header=TRUE, na.strings = "NA", sep=",", as.is=T, strip.white=T)

head(IndiStrata_fillNA)
head(stratsetq2)

PlotIndi_strata_withdatapoints(IndiStrata_fillNA)





Plot <- function(x) {
  ggplot(x, aes(YEAR, value, colour=variable,group=variable)) + #linetype = variable, 
    scale_color_brewer(palette="Paired") +
    #stat_smooth(se=F) + 
    geom_point() +
    facet_wrap( ~ Strata) +
    theme(text = element_text(size=15)) +
    theme(axis.title.x=element_blank()) + theme(axis.title.y=element_blank()) +
    theme(legend.title=element_blank()) +
    theme(legend.position='bottom') +
    #ggtitle("Ci (21%)") +
    theme(strip.text.x = element_text(size=13),
          strip.background = element_rect(fill="white"))
}



IndiStrata_fillNA <- melt(IndiStrata_fillNA,id=c('Year', 'Strata'), measure = c(#'Abundance',
                                                                  #'Abundance_s',
                                                                  'BInvertebrateToDemersal',
                                                                  #'BInvertebrateToDemersal_s',
                                                                  'Biomass',
                                                                  #'Biomass_s',
                                                                  'BiomassClupeids',
                                                                  #'BiomassClupeids_s',
                                                                  'BiomassFinfish',
                                                                  #'BiomassFinfish_s',
                                                                  'BiomassFlatfish',
                                                                  # 'BiomassFlatfish_s',
                                                                  'BiomassForage',
                                                                  #'BiomassForage_s',
                                                                  'BiomassGadoids',
                                                                  #'BiomassGadoids_s',
                                                                  'BiomassGroundfish',
                                                                  # 'BiomassGroundfish_s',
                                                                  'BiomassInvertebrates',
                                                                  #'BiomassInvertebrates_s',
                                                                  'BiomassSkates',
                                                                  #'BiomassSkates_s',
                                                                  'BiomassTL2',
                                                                  # 'BiomassTL2_s',
                                                                  'BiomassTL3',
                                                                  # 'BiomassTL3_s',
                                                                  'BiomassTL4',
                                                                  #'BiomassTL4_s',
                                                                  'BTGMediumBenthivore',
                                                                  #'BTGMediumBenthivore_s', 
                                                                  'BTGPiscivore',
                                                                  # 'BTGPiscivore_s',
                                                                  'BTGLargeBenthivore',
                                                                  # 'BTGLargeBenthivore_s',
                                                                  'BTGPlanktivore',
                                                                  # 'BTGPlanktivore_s',
                                                                  'BTGZoopiscivore',
                                                                  # 'BTGZoopiscivore_s',
                                                                  'BPelagicToDemersal',
                                                                  # 'BPelagicToDemersal_s',
                                                                  #'Heips',
                                                                  #  'Heips_s',
                                                                  'HillN1Diversity',
                                                                  #'HillN1Diversity_s',
                                                                  'HillN2Dominance',
                                                                  #'HillN2Dominance_s',
                                                                  'InverseCVBiomass',
                                                                  #'InverseCVBiomass_s',
                                                                  'KemptonQ',
                                                                  # 'KemptonQ_s',
                                                                  'LargeFishIndicator',
                                                                  # 'LargeFishIndicator_s',
                                                                  'LargeSpeciesIndicator',
                                                                  # 'LargeSpeciesIndicator_s',
                                                                  'MargalefGroundfish',
                                                                  #  'MargalefGroundfish_s',
                                                                  'MargalefRichness',
                                                                  #  'MargalefRichness_s',
                                                                  'MeanLengthAbundance',
                                                                  # 'MeanLengthAbundance_s',
                                                                  'MeanLengthBiomass',
                                                                  # 'MeanLengthBiomass_s',
                                                                  'MeanLifespan',
                                                                  #  'MeanLifespan_s',
                                                                  'MeanTrophicLevel',
                                                                  #  'MeanTrophicLevel_s',
                                                                  #'meanTrophicLevelCommunityLengthALLBIOMASS',
                                                                  #'meanTrophicLevelCommunityLengthALLBIOMASS_s',
                                                                  'MMLengthAbundance',
                                                                  #  'MMLengthAbundance_s',
                                                                  'MMLengthBiomass',
                                                                  #  'MMLengthBiomass_s',
                                                                  'PielouEvenness',
                                                                  #  'PielouEvenness_s',
                                                                  'PropPredatoryFish',
                                                                  #  'PropPredatoryFish_s',
                                                                  'ShannonDiversity',
                                                                  #  'ShannonDiversity_s',
                                                                  'SpeciesRichness',
                                                                  #   'SpeciesRichness_s', 
                                                                  'CCLargeBenthivore',
                                                                  #  'CCLargeBenthivore_s',
                                                                  'CCMediumBenthivore',
                                                                  #  'CCMediumBenthivore_s',
                                                                  'CCPiscivore',
                                                                  #  'CCPiscivore_s',
                                                                  'CCPlanktivore',
                                                                  #  'CCPlanktivore_s',
                                                                  'CCZoopiscivore',
                                                                  #  'CCZoopiscivore_s',
                                                                  #'CommunityCondition_s',
                                                                  'CommunityCondition'))

stratsetq2 <- melt(stratsetq2,id=c('Year', 'Strata'), measure = c(#'Abundance',
                                                                      #'Abundance_s',
                                                                      'BInvertebrateToDemersal',
                                                                      #'BInvertebrateToDemersal_s',
                                                                      'Biomass',
                                                                      #'Biomass_s',
                                                                      'BiomassClupeids',
                                                                      #'BiomassClupeids_s',
                                                                      'BiomassFinfish',
                                                                      #'BiomassFinfish_s',
                                                                      'BiomassFlatfish',
                                                                     # 'BiomassFlatfish_s',
                                                                      'BiomassForage',
                                                                      #'BiomassForage_s',
                                                                      'BiomassGadoids',
                                                                      #'BiomassGadoids_s',
                                                                      'BiomassGroundfish',
                                                                     # 'BiomassGroundfish_s',
                                                                      'BiomassInvertebrates',
                                                                      #'BiomassInvertebrates_s',
                                                                      'BiomassSkates',
                                                                      #'BiomassSkates_s',
                                                                      'BiomassTL2',
                                                                     # 'BiomassTL2_s',
                                                                      'BiomassTL3',
                                                                     # 'BiomassTL3_s',
                                                                      'BiomassTL4',
                                                                      #'BiomassTL4_s',
                                                                      'BTGMediumBenthivore',
                                                                      #'BTGMediumBenthivore_s', 
                                                                      'BTGPiscivore',
                                                                     # 'BTGPiscivore_s',
                                                                      'BTGLargeBenthivore',
                                                                     # 'BTGLargeBenthivore_s',
                                                                      'BTGPlanktivore',
                                                                     # 'BTGPlanktivore_s',
                                                                      'BTGZoopiscivore',
                                                                     # 'BTGZoopiscivore_s',
                                                                      'BPelagicToDemersal',
                                                                     # 'BPelagicToDemersal_s',
                                                                     # 'Heips',
                                                                    #  'Heips_s',
                                                                      'HillN1Diversity',
                                                                      #'HillN1Diversity_s',
                                                                      'HillN2Dominance',
                                                                      #'HillN2Dominance_s',
                                                                      'InverseCVBiomass',
                                                                      #'InverseCVBiomass_s',
                                                                      'KemptonQ',
                                                                     # 'KemptonQ_s',
                                                                      'LargeFishIndicator',
                                                                     # 'LargeFishIndicator_s',
                                                                      'LargeSpeciesIndicator',
                                                                     # 'LargeSpeciesIndicator_s',
                                                                      'MargalefGroundfish',
                                                                    #  'MargalefGroundfish_s',
                                                                      'MargalefRichness',
                                                                    #  'MargalefRichness_s',
                                                                      'MeanLengthAbundance',
                                                                     # 'MeanLengthAbundance_s',
                                                                      'MeanLengthBiomass',
                                                                     # 'MeanLengthBiomass_s',
                                                                      'MeanLifespan',
                                                                    #  'MeanLifespan_s',
                                                                      'MeanTrophicLevel',
                                                                    #  'MeanTrophicLevel_s',
                                                                      #'meanTrophicLevelCommunityLengthALLBIOMASS',
                                                                      #'meanTrophicLevelCommunityLengthALLBIOMASS_s',
                                                                      'MMLengthAbundance',
                                                                    #  'MMLengthAbundance_s',
                                                                      'MMLengthBiomass',
                                                                    #  'MMLengthBiomass_s',
                                                                      'PielouEvenness',
                                                                    #  'PielouEvenness_s',
                                                                      'PropPredatoryFish',
                                                                    #  'PropPredatoryFish_s',
                                                                      'ShannonDiversity',
                                                                    #  'ShannonDiversity_s',
                                                                      'SpeciesRichness',
                                                                   #   'SpeciesRichness_s', 
                                                                      'CCLargeBenthivore',
                                                                    #  'CCLargeBenthivore_s',
                                                                      'CCMediumBenthivore',
                                                                    #  'CCMediumBenthivore_s',
                                                                      'CCPiscivore',
                                                                    #  'CCPiscivore_s',
                                                                      'CCPlanktivore',
                                                                    #  'CCPlanktivore_s',
                                                                      'CCZoopiscivore',
                                                                    #  'CCZoopiscivore_s',
                                                                     # 'CommunityCondition_s',
                                                                      'CommunityCondition'))